#ifndef CONTENTTYPE_H_
#define CONTENTTYPE_H_

// Main states
// Content-type
#define O_CONTENTTYPE 49
#define N1_CONTENTTYPE 50
#define T1_CONTENTTYPE 51
#define E1_CONTENTTYPE 52
#define N2_CONTENTTYPE 53
#define T2_CONTENTTYPE 54
#define UNDERSCORE_CONTENTTYPE 55
#define T3_CONTENTTYPE 56
#define Y_CONTENTTYPE 57
#define P_CONTENTTYPE 58
#define E2_CONTENTTYPE 59
#define FINISHED_CONTENT_TYPE 60

#endif